[General]
Name = "Default"
Version = "0.9"
Creator = "Mr-Ojii"

[Genre]
"J-POP" = 1
"アニメ" = 2
"ゲームミュージック" = 3
"ナムコオリジナル" = 4
"クラシック" = 5
"バラエティ" = 6
"どうよう" = 7
"ボーカロイド" = 8
"VOCALOID" = 8

[Sound]
SENames = [ "太鼓", "クイーカ", "ウッドブロック" ]

[SongSelect]
BackBoxTextCorrectionY = 40
RotateChara = [ "≠", "【", "】", ":", "ー", "-", "~", "～", "<", ">", "(", ")", "[", "]", "「", "」", "（", "）", "＜", "＞", " ", "　", "『", "』" ]
CorrectionXChara = [ ".", "ッ", "ェ", "ョ", "ャ", "[", "]" ]
CorrectionXCharaValue = [ 10, 5, 7, 7, 7, -10, -10 ]

[Game]
NotesAnime = true

[Game.Chara]
BalloonX = [ 210, 210 ]
BalloonY = [ 0, 175 ]
BeatNormal = [ 1, 1 ]
BeatClear = [ 2, 2 ]
BeatGoGo = [ 2, 2 ]
MotionNormal = [
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1],
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1],
]
MotionClear = [
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1],
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1],
]
MotionGoGo = [
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29],
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29],
]

[Game.Dancer]
X = [ 640, 420, 860, 200, 1080 ]
Y = [ 580, 580, 580, 580, 580 ]
Motion = [ 0, 1, 2, 3, 4, 5 ]
Beat = 1

[Game.Mob]
Beat = 1
PtnBeat = 1

[Game.Balloon]
ComboNumberX = [ 312, 312 ]
ComboNumberY = [ 34, 580 ]
ComboNumberExX = [ 335, 335 ]
ComboNumberExY = [ 34, 580 ]
ComboTextX = [ 473, 473 ]
ComboTextY = [ 55, 601 ]
ComboTextExX = [ 498, 498 ]
ComboTextExY = [ 55, 601 ]

[Game.PuchiChara]
Width = 250
Height = 250
Ptn = 2
Scale = [ 0.5, 0.5 ]
Timer = 4000
X = [ 50, 50 ]
Y = [ 100, 637 ]
BalloonX = [ 310, 310 ]
BalloonY = [ 260, 500 ]

[Game.PanelFont]
StageText = "n曲目"

[Game.Background]
ScrollPattern = [ 0, 0 ]

[Game.DanC]
NumberPadding = 41
NumberSmallPadding = 23

[Game.Effect.FlyingNotes]
IsUsingEasing = false
