[General]
Name = "Default"
Version = "0.9"
Creator = "Takkkom"

[Genre]
"J-POP" = 1
"アニメ" = 2
"ゲームミュージック" = 3
"ナムコオリジナル" = 4
"クラシック" = 5
"バラエティ" = 6
"どうよう" = 7
"ボーカロイド" = 8
"VOCALOID" = 8

[Font]
MainFontName = "Fonts/MPLUSRounded1c-Medium.ttf"
LyricFontName = "Fonts/MPLUSRounded1c-Medium.ttf"

[Sound]
SENames = [ "太鼓", "クイーカ", "ウッドブロック" ]

[Overlay]
NetworkConnectionX = 1224
NetworkConnectionY = 665
NetworkConnectionSize = [ 40, 40 ]

[NamePlate]
ShadowX = 1
ShadowY = 2
PlayerNumberX = 0
PlayerNumberY = 0
DanBaseX = 0
DanBaseY = 27
NameSize = 17
NameX = 151
NameY = 45
NameWithDanX = 184
NameWithDanY = 45
TitleSize = 16
TitleBaseX = 0
TitleBaseY = 0
TitleX = 151
TitleY = 16

[SongSelect]
BackBoxTextCorrectionY = 40
RotateChara = [ "≠", "【", "】", ":", "ー", "-", "~", "～", "<", ">", "(", ")", "[", "]", "「", "」", "（", "）", "＜", "＞", " ", "　", "『", "』" ]
CorrectionXChara = [ ".", "ッ", "ェ", "ョ", "ャ", "[", "]" ]
CorrectionXCharaValue = [ 10, 5, 7, 7, 7, -10, -10 ]

[Game]
SENotesOffsetY = [ 131, 131 ]
JudgePointX = [ 413, 413 ]
JudgePointY = [ 256, 433 ]
ScrollFieldBGX = [ 332, 332 ]
ScrollFieldBGY = [ 192, 368 ]
NotesAnime = true

[Game.Chara]
X = [ -40, -40 ]
Y = [ -50, 487 ]
BalloonX = [ 143, 143 ]
BalloonY = [ -93, 205 ]
BalloonTimer = [ 25, 25 ]
BalloonDelay = [ 400, 400 ]
BalloonFadeOut = [ 84, 84 ]
BeatNormal = [ 1, 1 ]
BeatClear = [ 2, 2 ]
BeatGoGo = [ 2, 2 ]
MotionNormal = [
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1],
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1],
]
MotionClear = [
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1],
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1],
]
MotionGoGo = [
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29],
    [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29],
]

[Game.Dancer]
X = [ 640, 420, 860, 200, 1080 ]
Y = [ 580, 580, 580, 580, 580 ]
Motion = [ 0, 1, 2, 3, 4, 5 ]
Beat = 1

[Game.Mob]
Beat = 1
PtnBeat = 1

[Game.CourseSymbol]
X = [ 15, 15 ]
Y = [ 232, 368 ]

[Game.PanelFont]
MusicNameX = 1251
MusicNameY = 26
MusicNameFontSize = 30
SubTitleNameX = 1114
SubTitleNameY = 70
SubTitleNameFontSize = 15
GenreX = 1116
GenreY = 75
LyricX = 640
LyricY = 630
LyricFontSize = 38
StageText = "n曲目"
StageTextDisp = true

[Game.Score]
X = [ 19, 19 ]
Y = [ 229, 531 ]
AddX = [ 19, 19 ]
AddY = [ 192, 567 ]
AddBonusX = [ 19, 19 ]
AddBonusY = [ 139, 614 ]
Padding = 20
Size = [ 32, 40 ]

[Game.Taiko]
BackGroundX = [ 0, 0 ]
BackGroundY = [ 184, 360 ]
ScoreBaseX = [ 0, 0 ]
ScoreBaseY = [ 192, 488 ]
NamePlateX = [ 320, 320 ]
NamePlateY = [ 20, 636 ]
PlayerNumberX = [ 0, 0 ]
PlayerNumberY = [ 192, 368 ]
X = [ 176, 176 ]
Y = [ 187, 363 ]
ComboX = [ 249, 249 ]
ComboY = [ 271, 449 ]
ComboExX = [ 249, 249 ]
ComboExY = [ 269, 447 ]
ComboEx4X = [ 249, 249 ]
ComboEx4Y = [ 269, 447 ]
ComboPadding = [ 42, 48, 40 ]
ComboSize = [ 56, 64 ]
ComboSizeEx = [ 56, 64 ]
ComboScale = [ 1.0, 1.0, 0.85 ]
ComboScalingOffset = 10
ComboExScalingOffset = 3
ComboEx4ScalingOffset = 3
ComboTextX = [ 248, 248 ]
ComboTextY = [ 299, 475 ]
ComboTextSize = [ 100, 50 ]
ComboExIsJumping = true

[Game.Gauge]
X = [ 487, 487 ]
Y = [ 140, 528 ]
EdgeX = [ -160, -160 ]
EdgeY = [ -4, 0 ]
LineX = [ 4, 4 ]
LineY = [ 4, 4 ]
LineSize = [ 14, 44 ]
FlashX = [ -3, -3 ]
FlashY = [ -7, -5 ]
FlashSize = [ 24, 64 ]
SoulFireX = [ 735, 735 ]
SoulFireY = [ 25, 25 ]
SoulFireSize = [ 380, 380 ]
SoulFireCount = 8
SoulTextX = [ 700, 700 ]
SoulTextY = [ -6, -6 ]
SoulTextSize = [ 72, 64 ]
ClearTextX = [ 5, 5 ]
ClearTextY = [ 4, 24 ]
ClearTextSize = [ 56, 24 ]
Step = 14
RainbowSize = [ 704, 52 ]
RainbowFrameCount = 8
RainbowTimer = 50

[Game.Balloon]
ComboX = [ 264, 264 ]
ComboY = [ 16, 572 ]
ComboSize = [ 336, 136 ]
ComboShinX = [ 254, 254 ]
ComboShinY = [ 16, 572 ]
ComboShinSize = [ 336, 136 ]
ComboNumberX = [ 385, 385 ]
ComboNumberY = [ 32, 588 ]
ComboShinNumberX = [ 375, 375 ]
ComboShinNumberY = [ 52, 608 ]
ComboTextX = [ 391, 391 ]
ComboTextY = [ 58, 614 ]
ComboShinTextX = [ 381, 381 ]
ComboShinTextY = [ 78, 634 ]
ComboScoreX = [ 452, 460 ]
ComboScoreY = [ 90, 650 ]
ComboScorePadding = 20
ComboScoreTextX = [ 478, 483 ]
ComboScoreTextY = [ 90, 650 ]
BalloonX = [ 428, 428 ]
BalloonY = [ 137, 435 ]
BalloonFrameX = [ 399, 399 ]
BalloonFrameY = [ 34, 332 ]
BalloonNumberX = [ 486, 486 ]
BalloonNumberY = [ 133, 431 ]
RollFrameX = [ 234, 234 ]
RollFrameY = [ 9, 522 ]
RollNumberX = [ 386, 386 ]
RollNumberY = [ 129, 640 ]
NumberSize = [ 64, 72 ]
NumberPadding = 56
RollNumberScale = 1.000
BalloonNumberScale = 0.8

[Game.Effect.Roll]
StartPointX = [ 56, -10, 200, 345, 100, 451, 600, 260, -30, 534, 156, 363 ]
StartPointY = [ 720 ]
StartPointMultiX = [ [ 56, -10, 200, 345, 100, 451, 600, 260, -30, 534, 156, 363 ], [ 56, -10, 200, 345, 100, 451, 600, 260, -30, 534, 156, 363 ] ]
StartPointMultiY = [ [ 240 ], [ 360 ] ]
SpeedX = [ 0.6 ]
SpeedY = [ -0.6 ]
SpeedMultiX = [ [ 0.6 ], [ 0.6 ] ]
SpeedMultiY = [ [ -0.6 ], [ 0.6 ] ]

[Game.Effect.FireWorks]
Width = 256
Height = 256
Ptn = 13
Timer = 20
AddBlend = true
Timing = 20

[Game.Effect.GoGoSplash]
Width = 300
Height = 400
Ptn = 10
X = [ 120, 300, 520, 760, 980, 1160 ]
Y = [ 740, 730, 720, 720, 730, 740 ]
Rotate = true
Timer = 25
AddBlend = true

[Game.Effect.FlyingNotes]
StartPointX = [ 414, 414 ]
StartPointY = [ 260, 434 ]
EndPointX = [ 1225, 1225 ]
EndPointY = [ 164, 554 ]
Sine = 220
IsUsingEasing = true
Timer = 3

[Game.Effect.Fire]
Width = 390
Height = 390
Ptn = 8
AddBlend = true

[Game.Effect.Rainbow]
Timer = 7

[Game.Effect.HitBase]
Width = 150
Height = 150

[Game.Effect.HitExplosion]
Width = 260
Height = 260
BigWidth = 230
BigHeight = 230
AddBlend = true
BigAddBlend = true

[Game.PuchiChara]
Width = 250
Height = 250
Ptn = 2
Scale = [ 0.5, 0.5 ]
Timer = 4000
X = [ 50, 50 ]
Y = [ 100, 637 ]
BalloonX = [ 310, 310 ]
BalloonY = [ 260, 500 ]

[Game.Background]
ScrollPattern = [ 0, 0 ]

[Game.DanC]
NumberPadding = 41
NumberSmallPadding = 23
